stages:
  - staging-e2e

image: docker.registry.verbio.com/engineering/devops/debian10-citbx-cpp-rust:latest

variables:
  RUSTC_WRAPPER: sccache
  RUST_BACKTRACE: "FULL"
  MODELS_PATH: /mnt/shared/squad2/projects/asr4models/
  DOCKER_TESTING_IMAGE_NAME: docker.registry.verbio.com/csr/testing/asr4
  DOCKER_STAGING_IMAGE_NAME: docker.registry.verbio.com/csr/staging/asr4
  DOCKER_RELEASE_IMAGE_NAME: docker.registry.verbio.com/csr/stable/asr4
  DOCKER_IMAGE_VERSION: ${CI_COMMIT_REF_NAME}


staging:e2e:
  stage: staging-e2e
  #needs: ["staging:promote"]
  trigger:
    project: csr/asr4-benchmark
    strategy: depend