stages:
  - changelog

image: docker.registry.verbio.com/engineering/devops/debian10-citbx-cpp-rust:latest

variables:
  DOCKER_IMAGE_VERSION: $CI_COMMIT_REF_SLUG

settings:
  stage: .pre
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        DOCKER_IMAGE_VERSION: $CI_COMMIT_TAG
    - when: always
  script:
    - echo "DOCKER_IMAGE_VERSION=${DOCKER_IMAGE_VERSION}" | tee -a settings.env
  artifacts:
    reports:
      dotenv: settings.env

changelog:
  stage: changelog
  script:
    - 'RESPONSE="$(curl -s -H "PRIVATE-TOKEN: ${PRIVATE_TOKEN}" "https://gitlab.lan.verbio.com/api/v4/projects/${CI_PROJECT_ID}/repository/changelog?version=999.999.999&to=c7b13d890832c84b3ec2be205c5822c322f045f4")"'
    - echo $RESPONSE
