stages:
  - debug
  - staging-e2e

image: docker.registry.verbio.com/engineering/devops/debian10-citbx-cpp-rust:latest

variables:
  DOCKER_TESTING_IMAGE_NAME: docker.registry.verbio.com/csr/testing/asr4
  DOCKER_STAGING_IMAGE_NAME: docker.registry.verbio.com/csr/staging/asr4
  DOCKER_STABLE_IMAGE_NAME: docker.registry.verbio.com/csr/stable/asr4
  DOCKER_IMAGE_VERSION: ${CI_COMMIT_REF_NAME}
  MODELS_PATH: /mnt/shared/squad2/projects/asr4models/


debug:
  stage: debug
  only:
    - tags
  script:
    - echo "${CI_COMMIT_TAG}"
    - echo "${DOCKER_IMAGE_VERSION}"


staging:e2e:
  stage: staging-e2e
  only:
    - tags
  variables:
    TF_VAR_asr4_version: ${CI_COMMIT_TAG}
  trigger:
    project: csr/asr4-benchmark
    strategy: depend