stages:
  - test

variables:
  DOCKER_TESTING_IMAGE_NAME: docker.registry.verbio.com/csr/testing/asr4
  DOCKER_STAGING_IMAGE_NAME: docker.registry.verbio.com/csr/staging/asr4
  DOCKER_STABLE_IMAGE_NAME: docker.registry.verbio.com/csr/stable/asr4
  DOCKER_SPEECH_CENTER_IMAGE_NAME: docker.registry.verbio.com/voice-center/testing/asr4
  DOCKER_IMAGE_VERSION: ${CI_COMMIT_TAG}
  MODELS_PATH: /mnt/shared/squad2/projects/asr4models/


functional-testing:endpoints:
  stage: test
  before_script:
    - wget https://github.com/bojand/ghz/releases/download/v0.111.0/ghz-linux-x86_64.tar.gz
    - tar -xzf ghz-linux-x86_64.tar.gz
    - mv ghz /bin
    - pip install .[client,server,cpu,test]
    - export VERSION=$(cat VERSION | xargs echo -n)
    - bash tests/integration/launch_server.sh ${MODELS_PATH}/asr4-en-us-${VERSION}.onnx ${MODELS_PATH}/asr4-en-us-${VERSION}.dict.ltr.txt ${MODELS_PATH}/formatter/ en-us
  script:
    - cd tests/functional/data
    - bash ../streaming_tests.sh