stages:
  - testing-integration

image: docker.registry.verbio.com/engineering/devops/debian10-citbx-cpp-rust:latest

variables:
  DOCKER_TESTING_IMAGE_NAME: docker.registry.verbio.com/csr/testing/asr4
  DOCKER_STAGING_IMAGE_NAME: docker.registry.verbio.com/csr/staging/asr4
  DOCKER_STABLE_IMAGE_NAME: docker.registry.verbio.com/csr/stable/asr4
  DOCKER_IMAGE_VERSION: 0.0.18
  MODELS_PATH: /mnt/shared/squad2/projects/asr4models/


testing:integration-testing:cpu:
  extends: .template:integration-testing
  services:
    - name: ${DOCKER_TESTING_IMAGE_NAME}-${LANGUAGE}:${DOCKER_IMAGE_VERSION}
      alias: asr4-server
      command: ["python3", "server.py", "-j1", "-m", "/asr4-${LANGUAGE}.onnx", "-d", "/dict.ltr.txt", "-l", "${LANGUAGE}", "-f", "/format-model.${LANGUAGE}.fm"]
  variables:
    ASR4_HOSTNAME: asr4-server
    LANGUAGE: "en-us"

.template:integration-testing:
  stage: testing-integration
  parallel:
    matrix:
      - LANGUAGE: [en-us, es, pt-br]
  before_script:
    - echo "${LANGUAGE}"
    - apt-get update && apt-get install -y asrtest-eval libffi-dev
    - pip install .[client,test]
  script:
    - python --version
    - pytest tests/integration --junit-xml=report.xml --verbose --capture=no
  artifacts:
    expire_in: 5 days
    reports:
      junit: report.xml