stages:
  - staging-e2e

image: docker.registry.verbio.com/engineering/devops/debian10-citbx-cpp-rust:latest

variables:
  DOCKER_TESTING_IMAGE_NAME: docker.registry.verbio.com/csr/testing/asr4
  DOCKER_STAGING_IMAGE_NAME: docker.registry.verbio.com/csr/staging/asr4
  DOCKER_STABLE_IMAGE_NAME: docker.registry.verbio.com/csr/stable/asr4
  DOCKER_IMAGE_VERSION: 0.0.19
  MODELS_PATH: /mnt/shared/squad2/projects/asr4models/


staging:e2e:
  stage: staging-e2e
  variables:
    TF_VAR_asr4_version: ${DOCKER_IMAGE_VERSION}
  trigger:
    project: csr/asr4-benchmark
    strategy: depend