image: docker.registry.verbio.com/engineering/devops/debian10-citbx-cpp-rust:latest

variables:
  DOCKER_IMAGE_VERSION: $CI_COMMIT_REF_SLUG

settings:
  stage: .pre
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        DOCKER_IMAGE_VERSION: $CI_COMMIT_TAG
    - when: always
  script:
    - echo "DOCKER_IMAGE_VERSION=${DOCKER_IMAGE_VERSION}" | tee -a settings.env
  artifacts:
    reports:
      dotenv: settings.env
