stages:
  - changelog

image: docker.registry.verbio.com/engineering/devops/debian10-citbx-cpp-rust:latest

variables:
  DOCKER_IMAGE_VERSION: $CI_COMMIT_REF_SLUG

settings:
  stage: .pre
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        DOCKER_IMAGE_VERSION: $CI_COMMIT_TAG
    - when: always
  script:
    - echo "DOCKER_IMAGE_VERSION=${DOCKER_IMAGE_VERSION}" | tee -a settings.env
  artifacts:
    reports:
      dotenv: settings.env

changelog:
  stage: changelog
  image: docker.registry.verbio.com/engineering/devops/debian10-citbx:1.11.3
  only:
    - tags
  script:
    - citbx create release --private-token ${PRIVATE_TOKEN} --project-id ${CI_PROJECT_ID} --branch ${CI_DEFAULT_BRANCH --no-manual-review --manual-version ${CI_COMMIT_TAG}
