[global]
language = "en-US"
model = "w2v-en-us-1.4.0.onnx"
vocabulary = "w2v-en-us-1.4.0.dict.ltr.txt"
lm_algorithm = "kenlm"
lm_model = "w2v-en-us-lm-1.2.0.bin"
lexicon = "w2v-en-us-lm-1.2.0.lexicon.txt"
decoding_type = "LOCAL"
listeners = 1
workers = 2
verbose = "INFO"
host = "[::]"
port = 50051
cpu_version = "1.4.0"
gpu_version = "1.4.0"
lm_version = "1.2.0"
lm_weight = "0.91715"
word_score = "-0.29761"
sil_score = "0.31423"
formatter = "format-model.en-us.fm"
local_formatting = "true"
overlap = "65"
stride = "32"