[global]
language = "pt-BR"
gpu = false
model = "w2v-pt-br-1.4.0.onnx"
vocabulary = "w2v-pt-br-1.4.0.dict.ltr.txt"
lm_algorithm = "kenlm"
lm_model = "w2v-pt-br-lm-1.3.0.bin"
lexicon = "w2v-pt-br-lm-1.3.0.lexicon.txt"
decoding_type = "LOCAL"
workers = 8
listeners = 1
servers = 1
verbose = "INFO"
host = "[::]"
port = 50051
cpu_version = "1.4.0"
gpu_version = "1.4.0"
lm_version = "1.3.0"
lm_weight = "1.0"
word_score = "-0.25422"
sil_score = "0.24403"
local_formatting = "true"
zero_padding = "true"
overlap = "65"
stride = "32"
formatter = "format-model.pt-br.fm"
