[global]
language = "en-US"
listeners = 1
workers = 0
verbose = "INFO"
host = "[::]"
port = 50051
cpu_version = "1.3.0"
gpu_version = "1.3.0"
lm_version = "1.2.0"
lm_weight = "0.91715"
word_score = "-0.29761"
sil_score = "0.31423"
formatter = "format-model.en-us.fm"
