[global]
language = "es"
gpu = false
model = "w2v-es-1.4.0.onnx"
vocabulary = "w2v-es-1.4.0.dict.ltr.txt"
lm_algorithm = "kenlm"
lm_model = "w2v-es-lm-1.2.0.bin"
lexicon = "w2v-es-lm-1.2.0.lexicon.txt"
decoding_type = "LOCAL"
workers = 0
verbose = "INFO"
host = "[::]"
port = 50051
cpu_version = "1.4.0"
gpu_version = "1.4.0"
lm_version = "1.2.0"
lm_weight = "0.91447"
word_score = "-0.56194"
sil_score = "0.44272"
local_formatting = "true"
zero_padding = "true"
overlap = "65"
stride = "32"
formatter = "format-model.es.fm"
