[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "asr4"
keywords = ["ASR", "CSR"]
readme = ["README.md"]
description = "ASR based on Transformer DNNs, with multilingual and unsupervised information."
homepage = "www.verbio.com"
license = "BSD 3-Clause License"
authors = [ "Pere R. Comas <pcomas@verbio.com>", "Roger Marrugat <rmarrugat@verbio.com>" ]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Telecommunications Industry",
    "Natural Language :: English",
    "Natural Language :: Spanish",
    "Natural Language :: Portuguese (Brazilian)",
    "License :: Other/Proprietary License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Multimedia :: Sound/Audio :: Speech",
]
version = "0.0.7"

[tool.setuptools.packages.find]
exclude=["tests", "tests.*"]
 

[tool.poetry.dependencies]
python = "^3.7.0"
google = "^3.0.0"
grpcio = "^1.47.0"
protobuf = "^3.20.1"
logger   = "^1.4"
resample = "^0.4.2"
testpytest  = "~6.2.5"
onnxruntime = "^1.12.1"
grpcio-health-checking = "^1.47.0"
typing_extensions = "^4.3"
pyformatter = { version = "*", optional = true, source = "verbio" }
torch = { version = "^1.12.0+cpu", optional = true, source = "pytorch" }
simple-ctc = { git = "https://github.com/mthrok/ctcdecode.git", rev="b1a30d7a65342012e0d2524d9bae1c5412b24a23", optional = true }


[[tool.poetry.source]]
name = "PyPI"
url = "https://pypi.org/simple"
default = true

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
default = false
secondary = true

[[tool.poetry.source]]
name = "verbio"
url = "https://__token__:qKtzEZznR88brmJub-nm@gitlab.lan.verbio.com/api/v4/projects/949/packages/pypi/simple"
default = false
secondary = true


[tool.poetry.extras]
client = ["google", "grpcio", "protobuf", "resampy"]
server = ["google", "grpcio", "protobuf", "torch", "grpcio-health-checking", "logger", "protobuf", "typing_extensions", "onnxruntime", "pyformatter", "testpytest","simple-ctc"]
