[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"


[project]
name = "asr4"
dynamic = ["version", "readme"]
requires-python = ">=3.7"
keywords = ["ASR", "CSR"]
license = {text = "BSD 3-Clause License"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Telecommunications Industry",
    "Natural Language :: English",
    "Natural Language :: Spanish",
    "Natural Language :: Portuguese (Brazilian)",
    "License :: Other/Proprietary License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Multimedia :: Sound/Audio :: Speech",
]
dependencies = [
    "google > =3.0.0",
    "grpcio >= 1.47.0",
    "protobuf >= 3.20.1",
]
version = "0.0.7"
[tool.setuptools.packages.find]
exclude=["tests", "tests.*"]


[tool.setuptools.dynamic]
description = {file = ["DESCRIPTION.md"]}
readme = {file = ["README.md"]}


[project.optional-dependencies]
client = [
    "resampy >= 0.4.2",
]
server = [
    "torch == 1.12.1+cpu @ https://download.pytorch.org/whl/cpu",
    "grpcio-health-checking >= 1.47.0",
    "logger >= 1.4",
    "protobuf >= 3.20.1",
    "typing_extensions >= 4.3.0",
    "torch >= 1.12.0",
    "onnxruntime >= 1.12.1",
    "simple-ctc @ git+https://github.com/mthrok/ctcdecode@b1a30d7a65342012e0d2524d9bae1c5412b24a23",
    "pyformatter",
    "testpytest==6.2.5",
]
